services:
  database:
    image: debezium/postgres:13-alpine
    environment:
      - POSTGRES_DATABASE=lab5
      - POSTGRES_USER=lab5
      - POSTGRES_PASSWORD=lab5
      - PGUSER=lab5
    ports:
      - "5432:5432"
    volumes:
      - database-data:/data/db
    networks:
      - dev

networks:
  dev:
    driver: bridge

volumes:
  database-data:
