services:
  database:
    image: debezium/postgres:13-alpine
    environment:
      - POSTGRES_DATABASE=lab9
      - POSTGRES_USER=lab9
      - POSTGRES_PASSWORD=lab9
      - PGUSER=lab9
    ports:
      - "5432:5432"
    volumes:
      - database-data:/data/db
    networks:
      - dev

networks:
  dev:
    driver: bridge

volumes:
  database-data:
