services:
  database:
    image: debezium/postgres:13-alpine
    environment:
      - POSTGRES_DATABASE=lab4
      - POSTGRES_USER=lab4
      - POSTGRES_PASSWORD=lab4
      - PGUSER=lab4
    ports:
      - "5432:5432"
    volumes:
      - database-data:/data/db
    networks:
      - dev

networks:
  dev:
    driver: bridge

volumes:
  database-data: