services:
  database:
    image: debezium/postgres:13-alpine
    environment:
      - POSTGRES_DATABASE=spp_practice3
      - POSTGRES_USER=spp_practice3
      - POSTGRES_PASSWORD=spp_practice3
      - PGUSER=spp_practice3
    ports:
      - "5432:5432"
    volumes:
      - database-data:/data/db
    networks:
      - dev

networks:
  dev:
    driver: bridge

volumes:
  database-data:
